---
title: "MSDA6372 Project 1"
author: "Will Butler"
date: '2022-05-31'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
setwd("C:/Users/rwbut/Desktop/stats_2/Project1_Summer2022/MSDS_6372_Project1")

library(tseries)
library(forecast)
library(ggplot2)
library(tidyverse)

lifeX<-read.csv("Life Expectancy Datav2.csv")


```



install.packages("caret")
install.packages("rlang")
install.packages("pROC")
install.packages("mlbench")
## Libraries
library(caret)
library(pROC)
library(mlbench)

## replace empty values with NaN
```{r}
str(lifeX)

lifeX_noNull <- lifeX
lifeX_noNull[lifeX_noNull == ""] <- NaN
lifeX_noNull
lifeX_noNull[!is.na(lifeX_noNull$Life.expectancy),]

```

## create the test and train data sets

``` {r}
set.seed(123)
ind <- sample(2, nrow(lifeX), replace = T, prob = c(0.7, 0.3))
training <- lifeX[ind == 1,]
test <- lifeX[ind ==2,]
```



## rf model
library(randomForest)

```{r}
set.seed(321)

train_Control <- trainControl(method = "cv", number = 10)
rf <- randomForest(Life.expectancy~.,data=training, na.action = na.omit, trainControl= train_Control)

print(rf)

attributes(rf)

## importance of variables 
imp <- as.data.frame(varImp(rf))
imp <- data.frame(overall = imp$Overall, names = rownames(imp))
imp[order(imp$overall,decreasing = T),]
```
## test the rf model
```{r}
rfTest <- predict(rf, test)
length(test$Life.expectancy)
summary(rfTest)

pvodf <- data.frame(Predicted = rfTest, Observed = test$Life.expectancy)
print(pvodf)
model <- lm(Observed ~ Predicted, data = pvodf)
summary(model)$r.squared
summary(model)
ggplot(pvodf, aes(x=Predicted, y=Observed)) + geom_point() + geom_abline(intercept = 0, slope = 1, color = "red", size = 2)
(mean(model$residuals^2))
(1/length(test$Life.expectancy))*(sum(model$residuals^2))
AIC(model)
```







